"""ValorsBot model

Revision ID: 010ed3ae9fd3
Revises: 8966ddaa7b08
Create Date: 2024-07-01 23:51:15.374235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010ed3ae9fd3'
down_revision: Union[str, None] = '8966ddaa7b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.alter_column('a_mmr',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('b_mmr',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('mm_bot_user_match_stats', schema=None) as batch_op:
        batch_op.alter_column('mmr_before',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('mmr_change',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('mm_bot_user_summary_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top_winstreak', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('top_losestreak', sa.Integer(), nullable=True))
        batch_op.alter_column('mmr',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_summary_stats', schema=None) as batch_op:
        batch_op.alter_column('mmr',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('top_losestreak')
        batch_op.drop_column('top_winstreak')

    with op.batch_alter_table('mm_bot_user_match_stats', schema=None) as batch_op:
        batch_op.alter_column('mmr_change',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('mmr_before',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.alter_column('b_mmr',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('a_mmr',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
