"""ValorsBot model

Revision ID: 0af7584d0dbb
Revises: db107d076587
Create Date: 2024-09-29 07:10:21.467533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af7584d0dbb'
down_revision: Union[str, None] = 'db107d076587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_message', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_users', schema=None) as batch_op:
        batch_op.drop_column('role_message')

    # ### end Alembic commands ###
