"""ValorsBot model

Revision ID: 1403813c3aa2
Revises: b4f99c3cfeb0
Create Date: 2024-06-21 06:06:52.524048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1403813c3aa2'
down_revision: Union[str, None] = 'b4f99c3cfeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
