"""ValorsBot model

Revision ID: 19d7d490af12
Revises: 96f205be4eed
Create Date: 2024-06-29 03:45:01.471415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d7d490af12'
down_revision: Union[str, None] = '96f205be4eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_abandons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignored', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_abandons', schema=None) as batch_op:
        batch_op.drop_column('ignored')

    # ### end Alembic commands ###
