"""ValorsBot model

Revision ID: 1a55fed42c91
Revises: 3650f9ec10e1
Create Date: 2024-06-13 04:00:13.235703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a55fed42c91'
down_revision: Union[str, None] = '3650f9ec10e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_regions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.SmallInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_regions', schema=None) as batch_op:
        batch_op.drop_column('index')

    # ### end Alembic commands ###
