"""ValorsBot model

Revision ID: 1cc85a642d7c
Revises: e0fb5529a64b
Create Date: 2024-06-11 03:17:33.672231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc85a642d7c'
down_revision: Union[str, None] = 'e0fb5529a64b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mm_buttons_message', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('mm_buttons_periods', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mm_lfg_role', sa.BigInteger(), nullable=True))
        batch_op.drop_column('mm_queue_message')
        batch_op.drop_column('mm_queue_periods')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mm_queue_periods', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('mm_queue_message', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('mm_lfg_role')
        batch_op.drop_column('mm_buttons_periods')
        batch_op.drop_column('mm_buttons_message')

    # ### end Alembic commands ###
