"""ValorsBot model

Revision ID: 1e0b04a3790e
Revises: 635cc8120b46
Create Date: 2024-10-06 04:30:38.165999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0b04a3790e'
down_revision: Union[str, None] = '635cc8120b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.drop_column('mm_maps_phase')

    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.drop_column('maps_phase')

    with op.batch_alter_table('mm_bot_user_summary_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('momentum', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_summary_stats', schema=None) as batch_op:
        batch_op.drop_column('momentum')

    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maps_phase', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False))

    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mm_maps_phase', sa.SMALLINT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
