"""ValorsBot model

Revision ID: 238bf5358533
Revises: 21ea1af2756a
Create Date: 2024-06-26 12:24:12.007707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '238bf5358533'
down_revision: Union[str, None] = '21ea1af2756a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_platform_mappings', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['platform_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_platform_mappings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
