"""ValorsBot model

Revision ID: 2ff47dbd8399
Revises: 19d7d490af12
Create Date: 2024-06-29 05:07:58.337386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ff47dbd8399'
down_revision: Union[str, None] = '19d7d490af12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mm_bot_match_players',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('team', sa.Enum('A', 'B', name='team'), nullable=True),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['mm_bot_users.guild_id', 'mm_bot_users.user_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['mm_bot_matches.id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', 'match_id')
    )
    op.create_table('mm_bot_user_summary_stats',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('abandons', sa.Integer(), nullable=True),
    sa.Column('ct_starts', sa.Integer(), nullable=True),
    sa.Column('top_score', sa.Integer(), nullable=True),
    sa.Column('top_kills', sa.Integer(), nullable=True),
    sa.Column('top_assists', sa.Integer(), nullable=True),
    sa.Column('total_score', sa.Integer(), nullable=True),
    sa.Column('total_kills', sa.Integer(), nullable=True),
    sa.Column('total_deaths', sa.Integer(), nullable=True),
    sa.Column('total_assists', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['mm_bot_users.guild_id', 'mm_bot_users.user_id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.drop_table('mm_bot_match_users')
    op.drop_table('mm_bot_user_aggregate_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mm_bot_user_aggregate_stats',
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('games', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('losses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('abandons', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ct_starts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('top_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('top_kills', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('top_assists', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_kills', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_deaths', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_assists', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['mm_bot_users.guild_id', 'mm_bot_users.user_id'], name='mm_bot_user_aggregate_stats_guild_id_user_id_fkey'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', name='mm_bot_user_aggregate_stats_pkey')
    )
    op.create_table('mm_bot_match_users',
    sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('team', postgresql.ENUM('A', 'B', name='team'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['mm_bot_users.guild_id', 'mm_bot_users.user_id'], name='mm_bot_match_users_guild_id_user_id_fkey'),
    sa.ForeignKeyConstraint(['match_id'], ['mm_bot_matches.id'], name='mm_bot_match_users_match_id_fkey'),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', 'match_id', name='mm_bot_match_users_pkey')
    )
    op.drop_table('mm_bot_user_summary_stats')
    op.drop_table('mm_bot_match_players')
    # ### end Alembic commands ###
