"""ValorsBot model

Revision ID: 3afee7d7d484
Revises: 1531ab7839ab
Create Date: 2024-09-17 21:42:30.653309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3afee7d7d484'
down_revision: Union[str, None] = '1531ab7839ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mm_match_category', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.drop_column('mm_match_category')

    # ### end Alembic commands ###
