"""ValorsBot model

Revision ID: 516321a9e12e
Revises: 5ce657f798e9
Create Date: 2024-07-19 19:02:13.785113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '516321a9e12e'
down_revision: Union[str, None] = '5ce657f798e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_blocked_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('blocked_by', sa.BigInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_blocked_users', schema=None) as batch_op:
        batch_op.drop_column('blocked_by')

    # ### end Alembic commands ###
