"""ValorsBot model

Revision ID: 51a66e3a4913
Revises: c3f82dba9bc1
Create Date: 2024-06-12 11:00:17.521136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51a66e3a4913'
down_revision: Union[str, None] = 'c3f82dba9bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_regions',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('emoji', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['bot_settings.guild_id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'label')
    )
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_channel', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('region_message', sa.BigInteger(), nullable=True))

    with op.batch_alter_table('mm_bot_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('registered', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('team_a',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'bot_regions', ['guild_id', 'region'], ['guild_id', 'label'])
        batch_op.drop_column('joined')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('team_a',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('registered')
        batch_op.drop_column('region')

    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.drop_column('region_message')
        batch_op.drop_column('region_channel')

    op.drop_table('bot_regions')
    # ### end Alembic commands ###
