"""ValorsBot model

Revision ID: 5a5ea26a0a9b
Revises: 5b7bdb623c52
Create Date: 2025-04-12 02:22:48.917904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5ea26a0a9b'
down_revision: Union[str, None] = '5b7bdb623c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mm_last_ping', sa.TIMESTAMP(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.drop_column('mm_last_ping')

    # ### end Alembic commands ###
