"""ValorsBot model

Revision ID: 5ead3d9ef6bb
Revises: c61784fd0dd9
Create Date: 2025-04-06 08:57:48.222964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ead3d9ef6bb'
down_revision: Union[str, None] = 'c61784fd0dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
