"""ValorsBot model

Revision ID: 63d7aa9c3531
Revises: 1a55fed42c91
Create Date: 2024-06-13 18:05:33.412664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d7aa9c3531'
down_revision: Union[str, None] = '1a55fed42c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mm_queue_reminder', sa.Integer(), nullable=True))

    with op.batch_alter_table('mm_bot_queue_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_queue_users', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.drop_column('mm_queue_reminder')

    # ### end Alembic commands ###
