"""ValorsBot model

Revision ID: 66178d2a8fd6
Revises: 2ff47dbd8399
Create Date: 2024-06-29 11:40:34.617375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66178d2a8fd6'
down_revision: Union[str, None] = '2ff47dbd8399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_summary_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mmr', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_summary_stats', schema=None) as batch_op:
        batch_op.drop_column('mmr')

    # ### end Alembic commands ###
