"""ValorsBot model

Revision ID: 69e47a3b3c78
Revises: 96d6a6bc2499
Create Date: 2024-07-15 19:40:11.430629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e47a3b3c78'
down_revision: Union[str, None] = '96d6a6bc2499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
