"""ValorsBot model

Revision ID: 8312f0280e1d
Revises: 63d7aa9c3531
Create Date: 2024-06-13 19:00:45.937762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8312f0280e1d'
down_revision: Union[str, None] = '63d7aa9c3531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.alter_column('mm_queue_reminder',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.alter_column('mm_queue_reminder',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
