"""ValorsBot model

Revision ID: 8628a9250e96
Revises: 3b2a1e29f5bb
Create Date: 2024-06-19 07:11:05.259300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8628a9250e96'
down_revision: Union[str, None] = '3b2a1e29f5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
