"""ValorsBot model

Revision ID: 8966ddaa7b08
Revises: 66178d2a8fd6
Create Date: 2024-07-01 16:03:23.717061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8966ddaa7b08'
down_revision: Union[str, None] = '66178d2a8fd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abandoned_by', sa.ARRAY(sa.BigInteger()), nullable=True))

    with op.batch_alter_table('mm_bot_user_match_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mmr_before', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mmr_change', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rounds_played', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('abandoned', sa.Boolean(), nullable=True))
        batch_op.drop_column('mmr')

    with op.batch_alter_table('mm_bot_user_summary_stats', schema=None) as batch_op:
        batch_op.drop_column('abandons')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_summary_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abandons', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('mm_bot_user_match_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mmr', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('abandoned')
        batch_op.drop_column('rounds_played')
        batch_op.drop_column('mmr_change')
        batch_op.drop_column('mmr_before')

    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.drop_column('abandoned_by')

    # ### end Alembic commands ###
