"""ValorsBot model

Revision ID: 9696993298c4
Revises: e69cdd2aa75e
Create Date: 2024-06-21 05:46:32.546601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9696993298c4'
down_revision: Union[str, None] = 'e69cdd2aa75e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_map_picks', schema=None) as batch_op:
        batch_op.drop_constraint('mm_bot_user_map_picks_map_key', type_='unique')
        batch_op.drop_constraint('mm_bot_user_map_picks_match_id_key', type_='unique')
        batch_op.drop_constraint('mm_bot_user_map_picks_user_id_key', type_='unique')
        batch_op.create_unique_constraint('unique_user_match_map', ['user_id', 'match_id', 'map'])

    with op.batch_alter_table('mm_bot_user_side_picks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('unique_user_match_side', ['user_id', 'match_id', 'side'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_side_picks', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_match_side', type_='unique')
        batch_op.drop_column('id')

    with op.batch_alter_table('mm_bot_user_map_picks', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_match_map', type_='unique')
        batch_op.create_unique_constraint('mm_bot_user_map_picks_user_id_key', ['user_id'])
        batch_op.create_unique_constraint('mm_bot_user_map_picks_match_id_key', ['match_id'])
        batch_op.create_unique_constraint('mm_bot_user_map_picks_map_key', ['map'])

    # ### end Alembic commands ###
