"""ValorsBot model

Revision ID: 96d6a6bc2499
Revises: aa08ef5db5c1
Create Date: 2024-07-07 21:01:10.274258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import select, desc, text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96d6a6bc2499'
down_revision: Union[str, None] = 'aa08ef5db5c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.drop_column('abandoned_by')

    sql = text("SELECT id FROM mm_bot_matches ORDER BY id DESC LIMIT 1")
    connection = op.get_bind()
    result = connection.execute(sql).scalar()
    with op.batch_alter_table('mm_bot_user_abandons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_id', sa.Integer(), nullable=False, server_default=str(result)))
        batch_op.create_foreign_key(None, 'mm_bot_matches', ['match_id'], ['id'])
        batch_op.alter_column('match_id', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_abandons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('match_id')

    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abandoned_by', postgresql.ARRAY(sa.BIGINT()), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
