"""ValorsBot model

Revision ID: a65d748aa112
Revises: 8d4dacee140a
Create Date: 2024-06-21 06:01:17.737574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a65d748aa112'
down_revision: Union[str, None] = '8d4dacee140a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('b_side', sa.Enum('T', 'CT', name='side'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.drop_column('b_side')

    # ### end Alembic commands ###
