"""ValorsBot model

Revision ID: a732974f3a4c
Revises: 9696993298c4
Create Date: 2024-06-21 05:48:57.256415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a732974f3a4c'
down_revision: Union[str, None] = '9696993298c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_side_picks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('guild_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('match_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('side', sa.Enum('T', 'CT', name='side'), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.create_unique_constraint('unique_user_match_side', ['user_id', 'match_id', 'side'])
        batch_op.create_foreign_key(None, 'mm_bot_matches', ['match_id'], ['id'])
        batch_op.create_foreign_key(None, 'mm_bot_users', ['guild_id', 'user_id'], ['guild_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_side_picks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_user_match_side', type_='unique')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('side')
        batch_op.drop_column('match_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('guild_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
