"""ValorsBot model

Revision ID: a94fc6e69fd6
Revises: db07ca669aed
Create Date: 2024-06-19 20:44:54.089768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94fc6e69fd6'
down_revision: Union[str, None] = 'db07ca669aed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.alter_column('a_mmr',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('b_mmr',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.alter_column('b_mmr',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)
        batch_op.alter_column('a_mmr',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
