"""ValorsBot model

Revision ID: b5c2632203b1
Revises: 6ccb5bd786cb
Create Date: 2025-04-23 13:21:50.349280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c2632203b1'
down_revision: Union[str, None] = '6ccb5bd786cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_regions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('base_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('base_height', sa.Float(), nullable=True))

    with op.batch_alter_table('mm_bot_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lon', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('uncertainty', sa.Float(), nullable=True))

    with op.batch_alter_table('rcon_servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lon', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('uncertainty', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rcon_servers', schema=None) as batch_op:
        batch_op.drop_column('uncertainty')
        batch_op.drop_column('height')
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')

    with op.batch_alter_table('mm_bot_users', schema=None) as batch_op:
        batch_op.drop_column('uncertainty')
        batch_op.drop_column('height')
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')

    with op.batch_alter_table('bot_regions', schema=None) as batch_op:
        batch_op.drop_column('base_height')
        batch_op.drop_column('base_longitude')
        batch_op.drop_column('base_latitude')

    # ### end Alembic commands ###
