"""ValorsBot model

Revision ID: c159987e634d
Revises: 3afee7d7d484
Create Date: 2024-09-18 05:25:35.430034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c159987e634d'
down_revision: Union[str, None] = '3afee7d7d484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mm_bot_warned_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_id', sa.BigInteger(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('WARNING', 'LATE', 'LANGUAGE', name='warn'), nullable=False),
    sa.Column('ignored', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['mm_bot_users.guild_id', 'mm_bot_users.user_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['mm_bot_matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mm_bot_warned_users')
    # ### end Alembic commands ###
