"""ValorsBot model

Revision ID: c3f82dba9bc1
Revises: 
Create Date: 2024-06-11 22:29:53.874403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3f82dba9bc1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_settings',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('mm_buttons_channel', sa.BigInteger(), nullable=True),
    sa.Column('mm_buttons_message', sa.BigInteger(), nullable=True),
    sa.Column('mm_buttons_periods', sa.Text(), nullable=True),
    sa.Column('mm_queue_channel', sa.BigInteger(), nullable=True),
    sa.Column('mm_log_channel', sa.BigInteger(), nullable=True),
    sa.Column('mm_lfg_role', sa.BigInteger(), nullable=True),
    sa.Column('staff_channel', sa.BigInteger(), nullable=True),
    sa.Column('log_channel', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('guild_id')
    )
    op.create_table('mm_bot_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_channel', sa.BigInteger(), nullable=False),
    sa.Column('match_thread', sa.BigInteger(), nullable=True),
    sa.Column('a_thread', sa.BigInteger(), nullable=True),
    sa.Column('b_thread', sa.BigInteger(), nullable=True),
    sa.Column('a_vc', sa.BigInteger(), nullable=True),
    sa.Column('b_vc', sa.BigInteger(), nullable=True),
    sa.Column('map', sa.String(length=32), nullable=True),
    sa.Column('a_score', sa.SmallInteger(), nullable=True),
    sa.Column('b_score', sa.SmallInteger(), nullable=True),
    sa.Column('start_timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_timestamp', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mm_bot_users',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=32), nullable=True),
    sa.Column('mmr', sa.Integer(), nullable=False),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('team_a', sa.Text(), nullable=True),
    sa.Column('joined', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('guild_id', 'user_id')
    )
    op.create_table('mm_bot_match_bans',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('map', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['mm_bot_users.guild_id', 'mm_bot_users.user_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['mm_bot_matches.id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'match_id', 'user_id')
    )
    op.create_table('mm_bot_match_users',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=1), nullable=True),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['mm_bot_users.guild_id', 'mm_bot_users.user_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['mm_bot_matches.id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'user_id', 'match_id')
    )
    op.create_table('mm_bot_mmr_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('mmr', sa.Integer(), nullable=False),
    sa.Column('mmr_delta', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['mm_bot_users.guild_id', 'mm_bot_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mm_bot_queue_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('queue_channel', sa.BigInteger(), nullable=False),
    sa.Column('queue_expiry', sa.Integer(), nullable=True),
    sa.Column('in_queue', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'user_id'], ['mm_bot_users.guild_id', 'mm_bot_users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mm_bot_queue_users')
    op.drop_table('mm_bot_mmr_history')
    op.drop_table('mm_bot_match_users')
    op.drop_table('mm_bot_match_bans')
    op.drop_table('mm_bot_users')
    op.drop_table('mm_bot_matches')
    op.drop_table('bot_settings')
    # ### end Alembic commands ###
