"""ValorsBot model

Revision ID: d7cb8210177c
Revises: b5c2632203b1
Create Date: 2025-04-25 17:49:32.250012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7cb8210177c'
down_revision: Union[str, None] = 'b5c2632203b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_options', sa.ARRAY(sa.String(length=32)), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_matches', schema=None) as batch_op:
        batch_op.drop_column('map_options')

    # ### end Alembic commands ###
