"""ValorsBot model

Revision ID: db107d076587
Revises: c159987e634d
Create Date: 2024-09-19 03:52:35.939814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db107d076587'
down_revision: Union[str, None] = 'c159987e634d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mm_join_period', sa.SmallInteger(), nullable=True))
    op.execute('UPDATE bot_settings SET mm_join_period = 900')
    op.alter_column('bot_settings', 'mm_join_period', nullable=False)


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.drop_column('mm_join_period')

    # ### end Alembic commands ###
