"""ValorsBot model

Revision ID: dff70f081043
Revises: 238bf5358533
Create Date: 2024-06-27 01:29:29.665994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dff70f081043'
down_revision: Union[str, None] = '238bf5358533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mm_verified_role', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('register_channel', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('register_message', sa.BigInteger(), nullable=True))
        batch_op.drop_column('region_message')
        batch_op.drop_column('region_channel')

    with op.batch_alter_table('user_platform_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guild_id', sa.BigInteger(), nullable=False))
        batch_op.drop_constraint('unique_id_platform', type_='unique')
        batch_op.create_unique_constraint('unique_guild_user_platform', ['guild_id', 'user_id', 'platform'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_platform_mappings', schema=None) as batch_op:
        batch_op.drop_constraint('unique_guild_user_platform', type_='unique')
        batch_op.create_unique_constraint('unique_id_platform', ['user_id', 'platform'])
        batch_op.drop_column('guild_id')

    with op.batch_alter_table('bot_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_channel', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('region_message', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('register_message')
        batch_op.drop_column('register_channel')
        batch_op.drop_column('mm_verified_role')

    # ### end Alembic commands ###
