"""ValorsBot model

Revision ID: ee0e7129c2dc
Revises: d97d75534eae
Create Date: 2024-07-03 00:33:28.793150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0e7129c2dc'
down_revision: Union[str, None] = 'd97d75534eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_match_stats', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_guild_user_match', ['guild_id', 'user_id', 'match_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mm_bot_user_match_stats', schema=None) as batch_op:
        batch_op.drop_constraint('unique_guild_user_match', type_='unique')

    # ### end Alembic commands ###
