"""ValorsBot model

Revision ID: fec167b61f43
Revises: 69e47a3b3c78
Create Date: 2024-07-16 20:33:57.803119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec167b61f43'
down_revision: Union[str, None] = '69e47a3b3c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mm_bot_mods',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('mod', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['guild_id'], ['bot_settings.guild_id'], ),
    sa.PrimaryKeyConstraint('guild_id', 'mod')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mm_bot_mods')
    # ### end Alembic commands ###
