on:
  push:
    branches:
      - main

jobs:
  run_update:
    name: Run Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check for schema changes
        id: check_schema
        run: |
          git fetch origin main
          SCHEMA_CHANGED=$(git diff origin/main..HEAD -- src/utils/models.py alembic/ | wc -l)
          echo "schema_changed=$SCHEMA_CHANGED" >> $GITHUB_OUTPUT

      - name: Schema Update
        if: steps.check_schema.outputs.schema_changed != '0'
        run: |
          RESPONSE=$(curl -X POST "https://valorsbotapi.oblivius.dev/update?type=schema" \
          -H "Authorization: ${{ secrets.SCHEMA_UPDATE_API_KEY }}" \
          -H "Content-Type: application/json")
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          if [ "$HTTP_STATUS" != "200" ]; then
            echo "Error: $BODY"
            exit 1
          fi

      - name: Regular Update
        run: |
          RESPONSE=$(curl -X POST "https://valorsbotapi.oblivius.dev/update?type=regular" \
          -H "Authorization: ${{ secrets.UPDATE_API_KEY }}" \
          -H "Content-Type: application/json")
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')
          if [ "$HTTP_STATUS" != "200" ]; then
            echo "Error: $BODY"
            exit 1
          fi