on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: update
        run: |
          curl -X POST https://valorsbotapi.oblivius.dev/update -H "API-Key: ${{ secrets.UPDATE_API_KEY }}"