on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -f - -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull and build and start and purge
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd ${{ secrets.WORK_DIR }}
            git checkout ${{ secrets.MAIN_BRANCH }}
            git pull
            cd ../..
            docker-compose build --parallel
            docker-compose up -d
            docker images --format "{{.Repository}}:{{.Tag}}" | grep "valorsbot" | xargs -r docker rmi -f
            exit
          EOF
      - name: cleanup
        run: rm -rf ~/.ssh
