name: Update Application

on:
  push:
    branches:
      - main

jobs:
  run_update:
    name: Run Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Regular Update
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST "https://api.valorsleague.org/update?type=regular" \
          -H "Authorization: ${{ secrets.UPDATE_API_KEY }}")
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')
          if [ "$http_code" != "200" ]; then
            echo "Error: $body"
            exit 1
          fi
          echo "Regular update successful: $body"